import { hasLocale, NextIntlClientProvider } from "next-intl";
import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Cairo,
  Playpen_Sans_Hebrew,
} from "next/font/google";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playpenSansHebrew = Playpen_Sans_Hebrew({
  variable: "--font-playpen-sans-hebrew",
  subsets: ["hebrew"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["arabic"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  const fontClassName =
    locale === "ar"
      ? cairo.className
      : locale === "he"
        ? playpenSansHebrew.className
        : geistSans.className;

  return (
    <html
      lang={locale}
      dir={"rtl"}
      className={`${geistSans.variable} ${geistMono.variable} ${cairo.variable} ${playpenSansHebrew.variable} h-full antialiased`}
    >
      <body className={`${fontClassName} h-full bg-white text-gray-900`}>
        <NextIntlClientProvider locale={locale}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
